### PR TITLE
Fixing Issue #16: "Dead End" in Nastazie

### PR DESCRIPTION
**Pull request by Rezmason**
Rooms 144, 145 and 146 contain a wizard, a gate and no door. It's therefore possible to be stuck inside, by transforming into the species of the wizard and failing the gate's species requirement. I've replaced the gates with doors, so the player is free to leave.

Issue: https://github.com/hundredrabbits/Oquonie/issues/16

### CODE REVIEW

**Comment by neauoire** [comment]
Thanks for tackling this issue :) 
Very good response to the poster too <3

**Comment by neauoire** [comment]
Testing and pushing to live build!

**Comment by Rezmason** [comment]
This might help ;)

oquonie.stage.warp_to(143, 0, 1);
oquonie.player.transform("nemedique");
oquonie.spellbook.add_spell("neomine_133");
oquonie.spellbook.add_spell("neomine_139");

**Comment by neauoire** [comment]
AH! One step ahead of you. 
I've been playing oquonie like that for long enough ;)

**Pull request merged**
